apiVersion: apps/v1
kind: Deployment
metadata:
  name: turo-test
  namespace: turo
  annotations:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turo-test
  template:
    metadata:
      labels:
        app: turo-test
    spec:
      containers:
      - name: turo-test
        image: docker_image_replace
