apiVersion: apps/v1
kind: Deployment
metadata:
  name: turo-test
  namespace: kube_namespace
  annotations:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: turo-test
  template:
    metadata:
      labels:
        app: turo-test
    spec:
      containers:
      - name: turo-test
        image: docker_image_replace
        env:
          - name: DISPLAY_VALUE
            valueFrom:
              configMapKeyRef:
                name: index-display
                key: display_value
          - name: CONFIG_PAGE
            valueFrom:
              configMapKeyRef:
                name: config-page
                key: config_values
